const data={
    products:[
        {
            _id:'1',
            name:'Nike Slim shirt',
            category:'Shirts',
            image:'/images/p1.jpg',
            price:120,
            countInStock:10,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            Description:'high quality product',
        },
        {
            _id:'2',
            name:'Tetra Pack',
            category:'Shirts',
            image:'/images/p1.jpg',
            price:120,
            countInStock:20,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            Description:'high quality product',
        },
        {
            _id:'3',
            name:'Nike Slim shirt',
            category:'Shirts',
            image:'/images/p1.jpg',
            price:120,
            countInStock:0,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            Description:'high quality product',
        },
        {
            _id:'4',
            name:'Nike Slim shirt',
            category:'Shirts',
            image:'/images/p1.jpg',
            price:120,
            countInStock:1,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            Description:'high quality product',
        },
        {
            _id:'5',
            name:'Nike Slim shirt',
            category:'Shirts',
            image:'/images/p1.jpg',
            price:120,
            countInStock:30,
            brand:'Nike',
            rating:4.5,
            numReviews:10,
            Description:'high quality product',
        },
    ]
}

export default data;